### ISSUE TITLE
Unable to Add New Shears

### ISSUE THREAD

**Issue by Gelles** [defeatedcrow/HarvestWithDispenser#1]
Hello! 

I've been using this great mod for a while in default, and decided to add the new shears from Better Shears to the json, but I can't get them to work.

Tested on:
Forge .2815
Better Shears 1.3r
HarvestWithDispenser 1_1.0.2

I tested initially by trying to add all of the shears:

--------------
{"minecraft:shears": {"range": 2}},

{"bettershears:diamond_shears": {"range": 2}},
{"bettershears:obsidian_shears": {"range": 3 }},
{"bettershears:emerald_shears": {"range": 4 }}

--------------
But when that failed I just tried a substitution of the default value:

--------------
{
 "bettershears:emerald_shears": {
  "range": 2
 }
}

--------------

Neither of these work, the shears just get tossed into the world.

Any help would be appreciated. Thank you for your time!

**Comment by defeatedcrow** [comment]
Hello! Thank you for your report.
The problem that the json file can not be read correctly has been fixed in fab4e4d12ee09b8ec57209dba16865fccb2aa0a5.

Then there seems to be a grammatical error in your json description. Please be careful about the number of "{}".
```
{
"minecraft:shears": {"range": 2},
"bettershears:diamond_shears": {"range": 2},
"bettershears:obsidian_shears": {"range": 3 },
"bettershears:emerald_shears": {"range": 4 }
}
```
This may apply well. Please try with the new version.
New versions are available [here](https://github.com/defeatedcrow/HarvestWithDispenser/releases/tag/v1.0.3). Or it will be released to Curse Forge soon.

Thank you!
